# Generated by Django 4.2.7 on 2023-11-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='rainy_day_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
